#### Options ####
# My lovely fonts
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Bold
italic_font      JetBrainsMono Nerd Font Mono Italic
bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic

# Hide ligatures when cursor is on it
disable_ligatures cursor

# Cursor look
cursor_shape block
cursor_trail 5
cursor_trail_decay 0.1 0.4

# Set Height
font_size 10.0

# Disable Bell
enable_audio_bell no

# tpipeline tab bar
tab_bar_min_tabs 2

#### Theme ####
include kanagawa_fork.conf

#### Mappings ####
# Basically disable kitty_mod, so there are no default mappings and we can use ctrl+shift for herdr
kitty_mod ctrl+alt

# Kittens
# map ctrl+shift+i kitten unicode_input
# map ctrl+shift+u kitten hints --type url
# map ctrl+shift+f kitten hints --type path --program @
# map ctrl+shift+h kitten hints --type hash --program @

map ctrl+shift+r load_config_file
map ctrl+shift+e kitten hints
# map ctrl+shift+h kitten hints --type=hash --program @

#### Sessions ####
# Default startup session
startup_session sessions/herdr.conf
