#!/bin/bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

# script fails if any command has exit != 0
set -eu

### init all submodules ###
echo "Init all submodules"
cd "$HOME"
yadm submodule update --recursive --init

### hide README and LICENSE ###
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!LICENSE'

### change https to git repo url ###
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:primeapple/dotfiles.git"

### Execute all files in bootstrap directory ###
cd "$HOME/.config/yadm"
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
		echo "Executing file from bootstrap: $bootstrap"
        if ! "$bootstrap"; then
            echo "Error: bootstrap '$bootstrap' failed" >&2
            exit 1
        fi
    fi
done


