#!/usr/local/bin/fish

#### RVM - Ruby enVironment Manager
# see: https://rvm.io/rvm/install
echo "Installing RVM:"
# TODO: add keys to keyserver
# install rvm
curl -sSL https://get.rvm.io | bash -s stable --ruby
# install fish functions
curl -L --create-dirs -o ~/.config/fish/functions/rvm.fish https://raw.github.com/lunks/fish-nuggets/master/functions/rvm.fish
