#!/usr/local/bin/fish
fish_add_path ~/.bin
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install jorgebucaran/nvm.fish
fisher install IlanCosman/tide@v5
fisher install gazorby/fish-abbreviation-tips
