#!/bin/bash

# settings shell to fish, if it isn't yet
CURRENT_SHELL=${SHELL##*/}
if [[ ! "$CURRENT_SHELL" == "fish" ]]; then
	chsh -s $(which fish)
fi

# adding .bin folder to path
fish -c "
if not contains ~/.bin \$PATH
	fish_add_path ~/.bin
end
"

# adding nice fish greeting
fish -c "set -U fish_greeting 'Welcome to fish 🐟'"

# TODO: this does not work yet, it sometimes adds weird filenames to the fish_plugins file
# # manage fisher plugins, this should normally work through the fish_plugins file, but sadly does not
# fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
# fish -c "fisher install IlanCosman/tide@v5"
# fish -c "fisher install gazorby/fish-abbreviation-tips"
# fish -c "fisher install jethrokuan/z

# # running tide configure, maybe only do this, if there are no tide settings yet
# # fish -c "tide configure"

