#!/bin/bash

#### RVM - Ruby enVironment Manager
# see: https://rvm.io/rvm/install
echo "Installing RVM:"
# fetch the keys
# this is a little less secure than using gpg to fetch the keys, but at least it works
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
# install rvm
curl -sSL https://get.rvm.io | bash -s stable --ruby
# install fish functions
curl -L --create-dirs -o ~/.config/fish/functions/rvm.fish https://raw.github.com/lunks/fish-nuggets/master/functions/rvm.fish

echo "Installing latest Ruby as default:"
# we could also use ruby-head to get the head, --default gives the latest lts mri
rvm use --latest --default
