// dcg-opencode-plugin: generated by `dcg install --opencode` — do not edit.
// Routes every OpenCode bash tool call through dcg (Destructive Command
// Guard) before execution. Remove with `uninstall.sh` or by deleting this
// file. Docs: https://github.com/Dicklesworthstone/destructive_command_guard
const DCG_BIN = "/Users/toni/.local/bin/dcg";

export const DcgGuard = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      if (!input || input.tool !== "bash") return;
      const command = output?.args?.command;
      if (typeof command !== "string" || command.length === 0) return;

      let stdoutText;
      try {
        const proc = Bun.spawn([process.env.DCG_BIN || DCG_BIN], {
          stdin: new TextEncoder().encode(
            JSON.stringify({ tool_name: "Bash", tool_input: { command } })
          ),
          stdout: "pipe",
          stderr: "ignore",
          env: { ...process.env, OPENCODE: "1" },
        });
        stdoutText = await new Response(proc.stdout).text();
        await proc.exited;
      } catch (err) {
        // dcg missing or unrunnable is an infrastructure failure, not a
        // safety verdict: fail open, but say so.
        console.error(`[dcg] OpenCode guard could not run dcg: ${err}`);
        return;
      }

      const text = (stdoutText || "").trim();
      if (!text) return; // empty stdout = allow

      let decision;
      try {
        decision = JSON.parse(text);
      } catch {
        return; // non-JSON stdout: treat as allow (matches other harnesses)
      }
      const hso = decision.hookSpecificOutput;
      const verdict = hso && hso.permissionDecision;
      if (verdict === "deny" || verdict === "ask") {
        // OpenCode has no operator-review state, so `ask` fails closed.
        throw new Error(hso.permissionDecisionReason || "Blocked by dcg");
      }
    },
  };
};
