command_timeout = 1000

[package]
disabled = true

[kotlin]
disabled = true

[gcloud]
disabled = true

[username]
show_always = true
format = "[$user]($style) on "

[hostname]
ssh_only = false

[memory_usage]
disabled = false

[java]
disabled = true
