"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory$git_branch$git_state$git_status $fill$username$hostname$nodejs$aws$kubernetes$time$line_break$character'


[directory]
style = '#0087AF'
repo_root_style = 'bold #00AFFF'
before_repo_root_style = '#0087AF'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = '#5FD700'
truncation_length = 24
format = '[$branch]($style)'

[git_state]
style = '#FF0000'
format = ' [$state( $progress_current/$progress_total)]($style)'

[git_status]
style = '#5FD700'
format = '($conflicted$stashed$index_deleted$worktree_deleted$renamed$modified$index_typechanged$worktree_typechanged$staged$untracked$ahead_behind)'
conflicted = '[ ~$count](#FF0000)'
stashed   = '[ *$count](#5FD700)'
staged    = '[ +$count](#D7AF00)'
modified  = '[ !$count](#D7AF00)'
untracked = '[ ?$count](#00AFFF)'
ahead     = '[ ⇡$count](#5FD700)'
behind    = '[ ⇣$count](#5FD700)'
diverged  = '[ ⇣$behind_count ⇡$ahead_count](#5FD700)'
up_to_date = ''
renamed = '[ »$count](#D7AF00)'
worktree_deleted = '[ -$count](#FF0000)'
index_deleted = '[ -$count](#D7AF00)'
# Having something to distinguish these two would be super cool
worktree_typechanged = '[ $count](#D7AF00)'
index_typechanged = '[ $count](#D7AF00)'

[fill]
symbol = '·'
style = '#585858'

[username]
format = '[$user]($style)'
style = '#D7AF87'

[hostname]
format = '[@$hostname]($style) '
style = '#D7AF87'

[time]
disabled = false
format = ' [$time]($style)'
time_format = '%T'
style = '#5F8787'

[character]
success_symbol = '[❯](#5FD700)'
error_symbol = '[❯](#FF0000)'
format = '$symbol '

[nodejs]
format = '[$symbol($version )]($style)'

[aws]
format = '[$symbol ($profile )(\($region\) )]($style)'
symbol = ''
style = 'bold #FF9900'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'
disabled = false
style = 'bold blue'

# from https://github.com/starship/starship/issues/6101#issuecomment-2295210551
[[kubernetes.contexts]]
context_pattern = 'arn.*\/(?P<cluster>[\w\/-]+)'
context_alias = "$cluster"
