#!/bin/bash
# This script is used by git to generate a commit message template based on the current branch name.
# Supported parts are conventional commit types (`type`) and ticket numbers (`123` or `GH-123`)
# The branch name will result in a commit message template like this:
#  - type-some-description -> type:
#  - type-GH-123-description -> type: GH-123
#  - type-123-description -> type: #123
#  - 123-description -> #123
#  - 123-GH-124-description -> #123 GH-124
#  - some-description ->

COMMIT_MSG_FILE="$1"

# Abort during merges/rebases
LAST_EXIT_CODE=$?
if [ $LAST_EXIT_CODE -ne 0 ]; then
    exit 0
fi

# Abort if first line of commit message is not empty (merges, amend, etc.)
if [ -n "$(head -n 1 "$COMMIT_MSG_FILE")" ]; then
    exit 0
fi

# Abort on excluded branches
EXCLUDED_BRANCHES=("master" "main" "dev")
CURRENT_BRANCH=$(git symbolic-ref --quiet --short HEAD)
if [[ ${EXCLUDED_BRANCHES[*]} =~ $CURRENT_BRANCH ]]; then
    exit 0
fi

# Build array of conventional commit types
CONVENTIONAL_COMMIT_TYPES=("build" "chore" "ci" "docs" "feat" "fix" "perf" "refactor" "revert" "style" "test")
for type in "${CONVENTIONAL_COMMIT_TYPES[@]}"; do
    CONVENTIONAL_COMMIT_TYPES+=("$type!")
done

MESSAGE=""

# Split branchname by "/" char and store in BRANCH_PARTS
IFS='/' read -ra BRANCH_PARTS <<< "$CURRENT_BRANCH"

# Checking if it includes conventional commit (scope not supported)
if [[ ${CONVENTIONAL_COMMIT_TYPES[*]} =~ ${BRANCH_PARTS[0]} ]]; then
    MESSAGE="${BRANCH_PARTS[0]}: "
fi

if [ ${#BRANCH_PARTS[@]} -ge 2 ]; then
    # Split description by "/" char and store in DESCRIPTION_PARTS
    IFS='-' read -ra DESCRIPTION_PARTS <<< "${BRANCH_PARTS[1]}"

    # Checking and constructing the message if it includes reference
    if [[ ${DESCRIPTION_PARTS[0]} =~ ^[0-9]+$ ]]; then
        MESSAGE+="#${DESCRIPTION_PARTS[0]} "
        DESCRIPTION_PARTS=("${DESCRIPTION_PARTS[@]:1}")
    fi

    # Checking and constructing the message if it includes ticket number
    if [[ ${DESCRIPTION_PARTS[0]} =~ ^[A-Z]+$ ]] && [[ ${DESCRIPTION_PARTS[1]} =~ ^[0-9]+$ ]]; then
        MESSAGE+="${DESCRIPTION_PARTS[0]}-${DESCRIPTION_PARTS[1]} "
        DESCRIPTION_PARTS=("${DESCRIPTION_PARTS[@]:2}")
    fi
fi

# Write MESSAGE to the commit message file
sed -i "1s/.*/$MESSAGE/" "$COMMIT_MSG_FILE"
