name: Yadm Test
on:
  push:
jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: arch
            dockerfile: Dockerfile.arch
          - distro: debian
            dockerfile: Dockerfile.debian
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f .github/${{ matrix.dockerfile }} -t ${{ matrix.distro }}-yadm .github/
      - name: Run yadm-test script
        run: docker run --rm -e BRANCH="${{ github.ref_name }}" -e DISTRO="${{ matrix.distro }}" ${{ matrix.distro }}-yadm

  macos-test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install yadm
        run: brew install yadm
      - name: Run yadm-test script
        run: bash .github/yadm-test.sh
        env:
          BRANCH: ${{ github.ref_name }}
